#To see all output:

P1:
	glpsol -m nd30.pli --output nd30.txt --wcpxlp nd30.lp -d nd30.dat

P2:
	glpsol -m mn27.pli --output mn27.txt --wcpxlp mn27.lp -d mn27.dat

P3:
	glpsol -m ss2.pli --output ss2.txt --wcpxlp ss2.lp -d ss2.dat

P4:
	glpsol -m ss15.pli --output ss15.txt --wcpxlp ss15.lp -d ss15.dat

P5:
	glpsol -m mn22.pli --output mn22.txt --wcpxlp mn22.lp -d mn22.dat

MODEL:
	glpsol -m nd30.pli -d nd30.dat 
	glpsol -m mn27.pli -d mn27.dat
	glpsol -m ss2.pli  -d ss2.dat
	glpsol -m ss15.pli -d ss15.dat
	glpsol -m mn22.pli -d mn22.dat

