#To see all output:

EP1:
	glpsol -m nd30.pli --output nd30.txt --wcpxlp nd30.lp -d nd30.dat

EP2:
	glpsol -m mn27.pli --output mn27.txt --wcpxlp mn27.lp -d mn27.dat

EP3:
	glpsol -m ss2.pli --output ss2.txt --wcpxlp ss2.lp -d ss2.dat

EP4:
	glpsol -m ss15.pli --output ss15.txt --wcpxlp ss15.lp -d ss15.dat

EP5:
	glpsol -m mn22.pli --output mn22.txt --wcpxlp mn22.lp -d mn22.dat

MODEL:
	glpsol -m nd30.pli -d nd30.dat 
	glpsol -m mn27.pli -d mn27.dat
	glpsol -m ss2.pli  -d ss2.dat
	glpsol -m ss15.pli -d ss15.dat
	glpsol -m mn22.pli -d mn22.dat
P10:
	glpsol -m nd30.pli -d nd30/nd30.0.dat 
P11:
	glpsol -m nd30.pli -d nd30/nd30.1.dat --output nd30.txt --wcpxlp nd30.lp 
P12:
	glpsol -m nd30.pli -d nd30/nd30.2.dat 
P20:
	glpsol -m mn27.pli -d mn27/mn27.0.dat
P21:
	glpsol -m mn27.pli -d mn27/mn27.1.dat
P22:
	glpsol -m mn27.pli -d mn27/mn27.2.dat
P30:
	glpsol -m ss2.pli  -d ss2/ss2.0.dat
P31:
	glpsol -m ss2.pli  -d ss2/ss2.1.dat
P32:
	glpsol -m ss2.pli  -d ss2/ss2.2.dat
P40:
	glpsol -m ss15.pli -d ss15/ss15.0.dat
P41:
	glpsol -m ss15.pli -d ss15/ss15.1.dat
P42:
	glpsol -m ss15.pli -d ss15/ss15.2.dat
P50:
	glpsol -m mn22.pli -d mn22/mn22.0.dat
P51:
	glpsol -m mn22.pli -d mn22/mn22.1.dat
P52:
	glpsol -m mn22.pli -d mn22/mn22.2.dat

